language: android

android:
  components:
    - android-28
    - build-tools-28.0.3
    - extra-android-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'ndk;20.0.5594570'

script:
  - cd shell/android-studio
  - chmod +x gradlew
  - ./gradlew assembleDreamcastDebug --console=plain --parallel

before_deploy:
  - cd ../../
  - GIT_HASH=`git log --pretty=format:'%h' -n 1`
  - GIT_BUILD=`git describe --all --always`-$GIT_HASH
  - mkdir -p artifacts/$GIT_BUILD/
  - cp shell/android-studio/flycast/build/outputs/apk/dreamcast/debug/flycast-dreamcast-debug.apk artifacts/$GIT_BUILD/flycast-debug-$GIT_HASH.apk

deploy:
  provider: s3
  access_key_id: AKIAJOZQS4H2PHQWYFCA
  secret_access_key: $S3_SECRET_KEY
  bucket: flycast-builds
  local-dir: artifacts
  upload-dir: android
  acl: public_read
  skip_cleanup: true
  region: us-east-2
  on:
    all_branches: true
repo: flyinghead/flycast

